### ISSUE TITLE
Remove doesn't work correctly

### ISSUE THREAD

**Issue by zhiyzhan** [alyssaq/heap#1]
int main()
{
        int A[] = {3, 70, 4, 80,90,5,6,82,84,91,92,7,8};
        Heap h;
        h.makeHeap(A, 13);
        cout << h.toString() << endl;
        h.remove(80);
        cout << h.toString() << endl;
        return 0;

}

3 70 4 80 90 5 6 82 84 91 92 7 8
3 70 4 8 90 5 6 82 84 91 92 7 // It's not heap any more

**Comment by alyssaq** [comment]
Thanks for picking that up! I just fixed the remove() function 018bfaa7cf6df9f4d473abeff1387dbf1a4bc31c. I also added an example.cpp based on your usage.
